---
title: "11-IsletEndoC_proteomics"
author: "Kathryn Walters"
date: "2023-07-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries, warning=FALSE, message=FALSE, echo=FALSE}
library(Biostrings)
library(rlist)
library(ggVennDiagram)
library(readr)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(conflicted)
library(limma)
library(tidyverse)
library(readxl)
conflict_prefer("here", "here")
conflict_prefer("filter", "dplyr")
```


```{r load data, message=FALSE, warning=FALSE, echo=FALSE}
AllORFs <- read_csv(here("output", "GeneCollapsedORFs_AllPrograms.csv"))
AllORFs <- AllORFs %>% select(-AAseq) %>% unique()

geneInfo <- read_csv(here("accessories","gencode.v26.primary.info.csv.zip"), col_names = F, show_col_types = FALSE) 
colnames(geneInfo) <- c("gene_id","transcript_id","biotype","symbol")

tx2gene <- geneInfo[,c(2,1)]
```


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
#getting ORFquant list of ORFs found in proteomics
islets2_OQ <- read_tsv(here("proteomics", "ORFQuant", "Cyto24_set2", "ORF_Cytro24_set2_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(islets2_OQ) <- "ORF_ID"

islets3_OQ <- read_tsv(here("proteomics", "ORFQuant", "Cyto24_set3", "ORF_Cyto24_set3_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(islets3_OQ) <- "ORF_ID"

islets_OQall <- rbind(islets2_OQ, islets3_OQ) %>% unique()

endoC_OQ <- read_tsv(here("proteomics", "ORFQuant", "EndoC_IFN24", "ORF_EndoC_IFN24_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(endoC_OQ) <- "ORF_ID"


#getting RiboCode list of ORFs found in sBC proteomics
islets2_RC <- read_tsv(here("proteomics", "RiboCode", "Cyto24_set2", "Ribo_Cyto24_set2_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(islets2_RC) <- "ORF_ID"

islets3_RC <- read_tsv(here("proteomics", "RiboCode", "Cyto24_set3", "Ribo_Cyto24_set3_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(islets3_RC) <- "ORF_ID"

endoC_RC <- read_tsv(here("proteomics", "RiboCode", "EndoC_IFN24", "Ribo_Endo_IFN24_protein.tsv")) %>% filter(`Unique Spectral Count` > 1) %>% pull(`Protein ID`)%>% as.data.frame()
colnames(endoC_RC) <- "ORF_ID"

islets_RCall <- rbind(islets2_RC, islets3_RC) %>% unique()
```



```{r per software, message=FALSE, warning=FALSE, echo=FALSE}
#grabbing only annotated genes
RC_anno <- AllORFs %>% filter(ORF_type == "annotated" & program == "Ribocode")
OQ_anno <- AllORFs %>% filter(ORF_type == "annotated" & program == "ORFquant")

#asking if these identified ORFs have proteomic support for each cell line. 
#Start with ribocode 
RC_anno <- RC_anno %>% dplyr::mutate(EndoC = case_when(ORF_ID %in% endoC_RC$ORF_ID ~ 'Yes', !(ORF_ID %in% endoC_RC$ORF_ID) ~ 'No'))
RC_anno$EndoC %>% table()


RC_anno <- RC_anno %>% dplyr::mutate(islet = case_when(ORF_ID %in% islets_RCall$ORF_ID ~ 'Yes', !(ORF_ID %in% islets_RCall$ORF_ID) ~ 'No'))
RC_anno$islet %>% table()


#finally ORFquant
OQ_anno <- OQ_anno %>% dplyr::mutate(EndoC = case_when(ORF_ID %in% endoC_OQ$ORF_ID ~ 'Yes', !(ORF_ID %in% endoC_OQ$ORF_ID) ~ 'No'))
OQ_anno$EndoC %>% table()

OQ_anno <- OQ_anno %>% dplyr::mutate(islet = case_when(ORF_ID %in% islets_OQall$ORF_ID ~ 'Yes', !(ORF_ID %in% islets_OQall$ORF_ID) ~ 'No'))
OQ_anno$islet %>% table()


#making a table to get the number/count of ORF ids with proteomic support and those without. 

# compute unique levels in data frame
lvls <- unique(unlist(RC_anno[5:6]))
  
# apply the summation per value for Ribocode
t_RC <- sapply(RC_anno[5:6], 
               function(x) table(factor(x, levels = lvls, 
                                        ordered = TRUE))) %>% as.data.frame()

t_RC$program <- "Ribocode"
t_RC <- t_RC %>% rownames_to_column("ProteinSupport") %>% pivot_longer(!c(program, ProteinSupport), names_to = "cell_type", values_to = "count")


# apply the summation per value for ORFquant
t_OQ <- sapply(OQ_anno[5:6], 
               function(x) table(factor(x, levels = lvls, 
                                        ordered = TRUE))) %>% as.data.frame()
t_OQ$program <- "ORFquant"
t_OQ <- t_OQ %>% rownames_to_column("ProteinSupport") %>% pivot_longer(!c(program, ProteinSupport), names_to = "cell_type", values_to = "count")


barplotData <- rbind(t_RC, t_OQ)


#making plots
p_anno_proteoSupport_percet_cellLines <- ggplot(barplotData, aes(fill=ProteinSupport, y=count, x=cell_type)) + 
    geom_bar(position="fill", stat="identity") +
  facet_wrap(~program) + theme_minimal() + scale_fill_colorblind() + ylab("Percent") + xlab("")

p_anno_proteoSupport_percet_cellLines

ggsave(plot = p_anno_proteoSupport_percet_cellLines, filename = here("plots", "annoProteinSupport_percet_cellLines.pdf"), width = 4, height = 3)

p_anno_proteoSupport_count_cellLines <- ggplot(barplotData, aes(fill=ProteinSupport, y=count, x=cell_type)) + 
    geom_bar(position="stack", stat="identity") +
  facet_wrap(~program) + theme_minimal() + scale_fill_colorblind() + ylab("Counts") + xlab("")

p_anno_proteoSupport_count_cellLines

#ggsave(plot = p_anno_proteoSupport_count_cellLines, filename = here("plots", "annoProteinSupport_counts_cellLines.pdf"), width = 4, height = 3)


```




```{r per software, message=FALSE, warning=FALSE, echo=FALSE}
#grabbing only NON-annotated genes
NOTannoORFs <- AllORFs %>% filter(ORF_type != "annotated")

RC_NotAnno <- NOTannoORFs %>% filter(program == "Ribocode")
OQ_NotAnno <- NOTannoORFs %>% filter(program == "ORFquant")


```


```{r}
#asking if these identified nuORFs have proteomic support for each cell line. 
#Start with ribocode 
RC_NotAnno <- RC_NotAnno %>% dplyr::mutate(EndoC = case_when(ORF_ID %in% endoC_RC$ORF_ID ~ 'Yes', !(ORF_ID %in% endoC_RC$ORF_ID) ~ 'No'))
RC_NotAnno$EndoC %>% table()


RC_NotAnno <- RC_NotAnno %>% dplyr::mutate(islet = case_when(ORF_ID %in% islets_RCall$ORF_ID ~ 'Yes', !(ORF_ID %in% islets_RCall$ORF_ID) ~ 'No'))
RC_NotAnno$islet %>% table()


#finally ORFquant
OQ_NotAnno <- OQ_NotAnno %>% dplyr::mutate(EndoC = case_when(ORF_ID %in% endoC_OQ$ORF_ID ~ 'Yes', !(ORF_ID %in% endoC_OQ$ORF_ID) ~ 'No'))
OQ_NotAnno$EndoC %>% table()


OQ_NotAnno <- OQ_NotAnno %>% dplyr::mutate(islet = case_when(ORF_ID %in% islets_OQall$ORF_ID ~ 'Yes', !(ORF_ID %in% islets_OQall$ORF_ID) ~ 'No'))
OQ_NotAnno$islet %>% table()


#making a table to get the number/count of ORF ids with proteomic support and those without. 
  
# apply the summation per value for Ribocode
t_RC_NA <- sapply(RC_NotAnno[5:6], 
               function(x) table(factor(x, levels = lvls, 
                                        ordered = TRUE))) %>% as.data.frame()

t_RC_NA$program <- "Ribocode"
t_RC_NA <- t_RC_NA %>% rownames_to_column("ProteinSupport") %>% pivot_longer(!c(program, ProteinSupport), names_to = "cell_type", values_to = "count")


# apply the summation per value for ORFquant
t_OQ_NA <- sapply(OQ_NotAnno[5:6], 
               function(x) table(factor(x, levels = lvls, 
                                        ordered = TRUE))) %>% as.data.frame()
t_OQ_NA$program <- "ORFquant"
t_OQ_NA <- t_OQ_NA %>% rownames_to_column("ProteinSupport") %>% pivot_longer(!c(program, ProteinSupport), names_to = "cell_type", values_to = "count")


barplotData_NotAnno <- rbind(t_RC_NA, t_OQ_NA)

#making plots
p_NonAnno_proteoSupport_percet_cellLines <- ggplot(barplotData_NotAnno, aes(fill=ProteinSupport, y=count, x=cell_type)) + 
    geom_bar(position="fill", stat="identity") +
  facet_wrap(~program) + theme_minimal() + scale_fill_colorblind() + ylab("Percent") + xlab("")

p_NonAnno_proteoSupport_percet_cellLines

#ggsave(plot = p_NonAnno_proteoSupport_percet_cellLines, filename = here("plots", "nuORFProteinSupport_percet_cellLines.pdf"), width = 4, height = 3)

p_NonAnno_proteoSupport_count_cellLines <- ggplot(barplotData_NotAnno, aes(fill=ProteinSupport, y=count, x=cell_type)) + 
    geom_bar(position="stack", stat="identity") +
  facet_wrap(~program) + theme_minimal() + scale_fill_colorblind() + ylab("Counts") + xlab("")

p_NonAnno_proteoSupport_count_cellLines

#ggsave(plot = p_NonAnno_proteoSupport_count_cellLines, filename = here("plots", "nuORFProteinSupport_counts_cellLines.pdf"), width = 4, height = 3)

```


#Now going to do the same as above but broken into the individual nuORFs. Use facet_grid!
```{r proteomic support, message=FALSE, warning=FALSE, echo=FALSE}

proteomicsEndoC <- rbind(endoC_OQ, endoC_RC)
proteomicsIslet <- rbind(islets_RCall, islets_OQall)

AllORFs <- AllORFs %>% dplyr::mutate(EndoC = case_when(ORF_ID %in% proteomicsEndoC$ORF_ID ~ 'Yes', !(ORF_ID %in% proteomicsEndoC$ORF_ID) ~ 'No')) %>% dplyr::mutate(islet = case_when(ORF_ID %in% proteomicsIslet$ORF_ID ~ 'Yes', !(ORF_ID %in% proteomicsIslet$ORF_ID) ~ 'No')) 


AllORFs_proteo <- AllORFs[,c(2,4:6)]

EndoC_freq <- AllORFs_proteo %>% group_by(ORF_type, program, EndoC) %>% dplyr::summarise(Freq = n())
colnames(EndoC_freq) <- c("ORF_type", "program", "support", "freq")
EndoC_freq$cell <- "EndoC"

islet_freq <- AllORFs_proteo %>% group_by(ORF_type, program, islet) %>% dplyr::summarise(Freq = n())
colnames(islet_freq) <- c("ORF_type", "program", "support", "freq")
islet_freq$cell <- "islet"

tableProteomicSupport <- rbind(EndoC_freq, islet_freq)


tableProteomicSupport$ORF_type <- factor(tableProteomicSupport$ORF_type, order = TRUE, levels =c("annotated", 'novel', 'uORF', "dORF", "other"))
levels(tableProteomicSupport$ORF_type)

colors <- c("#969696", "#009E73", "#56B4E9", "#E69F00", "#CC79A7")

p_nuORF_proteoSupport_percent <- ggplot(tableProteomicSupport %>% filter(cell != "sBC" & ORF_type != "other"), aes(fill=support, y=freq, x=cell)) + geom_bar(position="fill", stat="identity") + theme_minimal() + scale_fill_manual(values = colors) + ylab("Percent Protein Support") + xlab("") +
  facet_grid(program ~ ORF_type) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p_nuORF_proteoSupport_percent

#ggsave(plot = p_nuORF_proteoSupport_percent, filename = here("plots", "nuORFProteinSupport_percent_cells_ORFfacet.pdf"), width = 4, height = 3)


p_nuORF_proteoSupport_count <- ggplot(tableProteomicSupport %>% filter(ORF_type != "annotated" & cell != "sBC"), aes(fill=support, y=freq, x=cell)) + geom_bar(position="stack", stat="identity") + theme_minimal() + scale_fill_colorblind() + ylab("Count of ORFs w/Proteomic Support") + xlab("") +
  facet_grid(program~ ORF_type) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p_nuORF_proteoSupport_count

#ggsave(plot = p_nuORF_proteoSupport_count, filename = here("plots", "nuORFProteinSupport_counts_cells_ORFfacet.pdf"), width = 7, height = 3)
```


#now doing the same as above, looking at specific nuORFs, but don't have it faceted by program. 
```{r warning=FALSE, message=FALSE, echo=FALSE}

AllORFs_collapsed <- AllORFs %>% column_to_rownames("ORF_ID")
AllORFs_collapsed <- AllORFs_collapsed[,-c(3)] %>% unique()

AllORFs_proteo_nProgram <- AllORFs[,c(2,4:6)]



EndoC_freq_NP <- AllORFs_proteo_nProgram %>% group_by(ORF_type, EndoC) %>% dplyr::summarise(Freq = n())
colnames(EndoC_freq_NP) <- c("ORF_type", "support", "freq")
EndoC_freq_NP$cell <- "EndoC"

islet_freq_NP <- AllORFs_proteo_nProgram %>% group_by(ORF_type, islet) %>% dplyr::summarise(Freq = n())
colnames(islet_freq_NP) <- c("ORF_type", "support", "freq")
islet_freq_NP$cell <- "islet"


tableProteomicSupport_NP <- rbind(EndoC_freq_NP, islet_freq_NP)


tableProteomicSupport_NP$ORF_type <- factor(tableProteomicSupport_NP$ORF_type, order = TRUE, levels =c("annotated", 'novel', 'uORF', "dORF", "other"))
levels(tableProteomicSupport_NP$ORF_type)

p_nuORF_proteoSupport_percent_NP <- ggplot(tableProteomicSupport_NP %>% filter(cell == "islet" & ORF_type != "other"), aes(fill=support, y=freq, x=ORF_type)) + geom_bar(position="fill", stat="identity") + theme_minimal() + scale_fill_colorblind() + ylab("Percent Protein Support") + xlab("") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p_nuORF_proteoSupport_percent_NP

#ggsave(plot = p_nuORF_proteoSupport_percent_NP, filename = here("plots", "nuORFProteinSupport_percent_cells_ORFfacet_NP_islet.pdf"), width = 4, height = 3)


p_nuORF_proteoSupport_count_NP <- ggplot(tableProteomicSupport_NP %>% filter(cell == "islet" & ORF_type =="annotated"), aes(fill=support, y=freq, x=cell)) + geom_bar(position="stack", stat="identity") + theme_minimal() + scale_fill_colorblind() + ylab("Count of ORFs w/Proteomic Support") + xlab("") +
  facet_grid(~ORF_type) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p_nuORF_proteoSupport_count_NP

#ggsave(plot = p_nuORF_proteoSupport_count_NP, filename = here("plots", "nuORFProteinSupport_counts_cells_ORFfacet_NP.pdf"), width = 7, height = 3)

p_nuORF_proteoSupport_count_NP2 <- ggplot(tableProteomicSupport_NP %>% filter(cell == "islet" & ORF_type !="annotated" & ORF_type !="other"), aes(fill=support, y=freq, x=cell)) + geom_bar(position="stack", stat="identity") + theme_minimal() + scale_fill_colorblind() + ylab("Count of ORFs w/Proteomic Support") + xlab("") +
  facet_grid(~ORF_type) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p_nuORF_proteoSupport_count_NP2

#ggsave(plot = p_nuORF_proteoSupport_count_NP2, filename = here("plots", "nuORFProteinSupport_counts_cells_ORFfacet_NP2.pdf"), width = 7, height = 3)

```


